### PR TITLE
Use PHP password_* Methods

### PR DESCRIPTION
**Pull request by amayer5125**
SHA1 is considered very weak for things like password stores. Even the [PHP docs](https://www.php.net/manual/en/function.sha1.php) recommend against using it for passwords.

### CODE REVIEW

**Comment by degecko** [comment]
Thank you for taking the time to submit this change, however, I decided to improve the password security in a slightly different way, so this specific pull request will not be necessary.

**Comment by amayer5125** [comment]
Your new implementation is more insecure than the first implementation. Anyone that can read the cookie value can get the original password in plaintext. With the implementation in this pull request the only way to get the plaintext password is brute force which would take thousands of years with current computer hardware.

Getting the plaintext password is as simple as grabbing the cookie value and passing it to this script:
```php
[$payload, $iv] = array_map('base64_decode', explode(' ', urldecode($argv[1])));
$password = openssl_decrypt($payload, 'blowfish', 'f1f9339c3389d679d3e641df713030bfbcb3882f', iv: $iv);
echo "Your password is: $password\n";
```

Copy the value from your browser
image

And run the script
```sh
$ php decrypt-password.php 'WHRNQi9DTHNjaW1EN3BXUXI2ekhMQWNNYStCZkFxRDE%3D+HoBZ7De2nXY%3D'
Your password is: MySecretPassword
```

**Comment by degecko** [comment]
> Anyone that can read the cookie value can get the original password in plaintext.

Why would anybody have access to my cookies? That'd be a vulnerability in itself. And if they have the cookie hash, they can use the cookie for themselves, as it is. Encrypted in 100 different ways, it doesn't even matter if the encryption is reversible. They'd just use that cookie as it is and they'd get access. But, again, how and why would anybody get access to the cookie?

It's weakly encrypted in the cookie to make sure that it gets protected from sniffing/MITM just in case somebody uses this without SSL.

What I upgraded in terms of security is actually passing the password through the form or the CLI.

**Comment by amayer5125** [comment]
There are tons of ways to get cookies from other sites. I'm not arguing that. The point I'm making is that if someone does get access to your cookie they can very easily get your password in plaintext. That is bad part. I know people should be using different passwords for every website, but let's be real, people don't.

I agree if someone was trying to "hack" the gbin website they would just use a copy of your cookie. But what if the person running the gbin website was the target? Now I have a plaintext copy of their password and I can try that against other sites I think the person might use (facebook, gmail, twitter, linkedin, etc).

Encrypting the password and putting it in a cookie opens people up to these types of attacks.

**Pull request closed without merging**
